/* Generated by generate_flags.py - Do not edit directly */
package com.android.launcher3;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

public class FeatureFlagsImpl implements FeatureFlags {
    private final Map<String, Boolean> mOverrides = new ConcurrentHashMap<>();

    public void setFlag(String flagName, boolean value) {
        mOverrides.put(flagName, value);
    }

    public void clearFlag(String flagName) {
        mOverrides.remove(flagName);
    }

    @Override
    public boolean allAppsSurface() {
        Boolean override = mOverrides.get("all_apps_surface");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean appLaunchBlur() {
        Boolean override = mOverrides.get("app_launch_blur");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean avoidDisplayCutoutBubbleBar() {
        Boolean override = mOverrides.get("avoid_display_cutout_bubble_bar");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean bindModelUsingRepository() {
        Boolean override = mOverrides.get("bind_model_using_repository");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean blurOnMoreSurfaces() {
        Boolean override = mOverrides.get("blur_on_more_surfaces");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean blurredHomeAnimation() {
        Boolean override = mOverrides.get("blurred_home_animation");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean centerSpringLoadedStateVertically() {
        Boolean override = mOverrides.get("center_spring_loaded_state_vertically");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean condoPlanner() {
        Boolean override = mOverrides.get("condo_planner");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean disableAppAutomationBlur() {
        Boolean override = mOverrides.get("disable_app_automation_blur");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean doubleTapToSleep() {
        Boolean override = mOverrides.get("double_tap_to_sleep");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableAllAppsButtonInHotseat() {
        Boolean override = mOverrides.get("enable_all_apps_button_in_hotseat");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableAllAppsEduForOverswipe() {
        Boolean override = mOverrides.get("enable_all_apps_edu_for_overswipe");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableAltTabKqsFlatenning() {
        Boolean override = mOverrides.get("enable_alt_tab_kqs_flatenning");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableAppAutomationIndicator() {
        Boolean override = mOverrides.get("enable_app_automation_indicator");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableAppLockShortcut() {
        Boolean override = mOverrides.get("enable_app_lock_shortcut");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableCollapseSysuiPanelsOnTaskbarClick() {
        Boolean override = mOverrides.get("enable_collapse_sysui_panels_on_taskbar_click");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableComposeForOptionsPopupMenuDialog() {
        Boolean override = mOverrides.get("enable_compose_for_options_popup_menu_dialog");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableContrastTiles() {
        Boolean override = mOverrides.get("enable_contrast_tiles");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableCueBarDesktopFormFactor() {
        Boolean override = mOverrides.get("enable_cue_bar_desktop_form_factor");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableCursorDrivenWorkflows() {
        Boolean override = mOverrides.get("enable_cursor_driven_workflows");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableCustomHeightForAllAppsOnCd() {
        Boolean override = mOverrides.get("enable_custom_height_for_all_apps_on_cd");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableDragStartEndMultiDispatch() {
        Boolean override = mOverrides.get("enable_drag_start_end_multi_dispatch");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableExpandingPauseWorkButton() {
        Boolean override = mOverrides.get("enable_expanding_pause_work_button");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableExpressiveFolderExpansion() {
        Boolean override = mOverrides.get("enable_expressive_folder_expansion");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableFallbackOverviewInWindow() {
        Boolean override = mOverrides.get("enable_fallback_overview_in_window");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableFileSystemFoldersAsDropTargets() {
        Boolean override = mOverrides.get("enable_file_system_folders_as_drop_targets");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableFixedQsbAtBottom() {
        Boolean override = mOverrides.get("enable_fixed_qsb_at_bottom");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableFocusOutline() {
        Boolean override = mOverrides.get("enable_focus_outline");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableFolderRefactor() {
        Boolean override = mOverrides.get("enable_folder_refactor");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableGrowthNudge() {
        Boolean override = mOverrides.get("enable_growth_nudge");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableHomeScreenFilesCopyPaste() {
        Boolean override = mOverrides.get("enable_home_screen_files_copy_paste");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableHomeScreenFilesRenaming() {
        Boolean override = mOverrides.get("enable_home_screen_files_renaming");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableHomeScreenFilesTrashing() {
        Boolean override = mOverrides.get("enable_home_screen_files_trashing");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableKqsForceTakeRunningTaskThumbnail() {
        Boolean override = mOverrides.get("enable_kqs_force_take_running_task_thumbnail");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableLaterIsLockedCheck() {
        Boolean override = mOverrides.get("enable_later_is_locked_check");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableLauncherIconShapes() {
        Boolean override = mOverrides.get("enable_launcher_icon_shapes");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableLauncherOverviewInWindow() {
        Boolean override = mOverrides.get("enable_launcher_overview_in_window");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableLowResThumbnailPreloading() {
        Boolean override = mOverrides.get("enable_low_res_thumbnail_preloading");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableMouseInteractionChanges() {
        Boolean override = mOverrides.get("enable_mouse_interaction_changes");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableMultiInstanceMenuTaskbar() {
        Boolean override = mOverrides.get("enable_multi_instance_menu_taskbar");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableNarrowGridRestore() {
        Boolean override = mOverrides.get("enable_narrow_grid_restore");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableNewTouchpadGestures() {
        Boolean override = mOverrides.get("enable_new_touchpad_gestures");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableOverviewDesktopTileWallpaperBackground() {
        Boolean override = mOverrides.get("enable_overview_desktop_tile_wallpaper_background");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableOverviewPagination() {
        Boolean override = mOverrides.get("enable_overview_pagination");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableOverviewSelectTextView() {
        Boolean override = mOverrides.get("enable_overview_select_text_view");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enablePredictiveBackInOverview() {
        Boolean override = mOverrides.get("enable_predictive_back_in_overview");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enablePrivateSpace() {
        Boolean override = mOverrides.get("enable_private_space");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableQsbOnHotseat() {
        Boolean override = mOverrides.get("enable_qsb_on_hotseat");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableRebootUnlockAnimation() {
        Boolean override = mOverrides.get("enable_reboot_unlock_animation");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableRecentsWindowBlur() {
        Boolean override = mOverrides.get("enable_recents_window_blur");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableRecentsWindowProtoLog() {
        Boolean override = mOverrides.get("enable_recents_window_proto_log");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableRefactorDigitalWellbeingToast() {
        Boolean override = mOverrides.get("enable_refactor_digital_wellbeing_toast");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableResponsiveWorkspace() {
        Boolean override = mOverrides.get("enable_responsive_workspace");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableRestoredbtaskModelwriterRefactor() {
        Boolean override = mOverrides.get("enable_restoredbtask_modelwriter_refactor");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableReversibleHomeActionCorner() {
        Boolean override = mOverrides.get("enable_reversible_home_action_corner");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableSaveActionInOverviewShare() {
        Boolean override = mOverrides.get("enable_save_action_in_overview_share");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableScalabilityForDesktopExperience() {
        Boolean override = mOverrides.get("enable_scalability_for_desktop_experience");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableSimultaneousOverviewTriggerOnExtendedDesktop() {
        Boolean override = mOverrides.get("enable_simultaneous_overview_trigger_on_extended_desktop");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableStateManagerProtoLog() {
        Boolean override = mOverrides.get("enable_state_manager_proto_log");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableStrictMode() {
        Boolean override = mOverrides.get("enable_strict_mode");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableSupportForArchiving() {
        Boolean override = mOverrides.get("enable_support_for_archiving");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableSwipeUpMagneticDetach() {
        Boolean override = mOverrides.get("enable_swipe_up_magnetic_detach");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableSystemDrag() {
        Boolean override = mOverrides.get("enable_system_drag");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableSystemDragToOtherApps() {
        Boolean override = mOverrides.get("enable_system_drag_to_other_apps");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableTaskbarA11YMoreOptionsButton() {
        Boolean override = mOverrides.get("enable_taskbar_a11y_more_options_button");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableTaskbarBehindShade() {
        Boolean override = mOverrides.get("enable_taskbar_behind_shade");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableTaskbarCustomization() {
        Boolean override = mOverrides.get("enable_taskbar_customization");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableTaskbarDragAndDrop() {
        Boolean override = mOverrides.get("enable_taskbar_drag_and_drop");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableTaskbarDragToRemove() {
        Boolean override = mOverrides.get("enable_taskbar_drag_to_remove");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableTaskbarIconContainer() {
        Boolean override = mOverrides.get("enable_taskbar_icon_container");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableTaskbarIconDesktopClicks() {
        Boolean override = mOverrides.get("enable_taskbar_icon_desktop_clicks");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableTaskbarNoRecreate() {
        Boolean override = mOverrides.get("enable_taskbar_no_recreate");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableTaskbarPinning() {
        Boolean override = mOverrides.get("enable_taskbar_pinning");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableTaskbarUiThread() {
        Boolean override = mOverrides.get("enable_taskbar_ui_thread");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableTasksDragAndDropInOverview() {
        Boolean override = mOverrides.get("enable_tasks_drag_and_drop_in_overview");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableTransactionalModelWriter() {
        Boolean override = mOverrides.get("enable_transactional_model_writer");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableTwoPaneLauncherSettings() {
        Boolean override = mOverrides.get("enable_two_pane_launcher_settings");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableTwolineAllapps() {
        Boolean override = mOverrides.get("enable_twoline_allapps");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableTwolineToggle() {
        Boolean override = mOverrides.get("enable_twoline_toggle");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableUnfoldStateAnimation() {
        Boolean override = mOverrides.get("enable_unfold_state_animation");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableWidgetPickerBlur() {
        Boolean override = mOverrides.get("enable_widget_picker_blur");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableWidgetsSectionInOptionsMenu() {
        Boolean override = mOverrides.get("enable_widgets_section_in_options_menu");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableWorkspacePageAnimation() {
        Boolean override = mOverrides.get("enable_workspace_page_animation");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enableWorkspaceSelection() {
        Boolean override = mOverrides.get("enable_workspace_selection");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean enabledFoldersInAllApps() {
        Boolean override = mOverrides.get("enabled_folders_in_all_apps");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean expandableLongPressMenu() {
        Boolean override = mOverrides.get("expandable_long_press_menu");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean fallbackRevealAnimation() {
        Boolean override = mOverrides.get("fallback_reveal_animation");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean fixWidgetSinglePtrResize() {
        Boolean override = mOverrides.get("fix_widget_single_ptr_resize");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean floatingSearchBar() {
        Boolean override = mOverrides.get("floating_search_bar");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean forceMonochromeAppIcons() {
        Boolean override = mOverrides.get("force_monochrome_app_icons");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean forceMonochromeAppIconsAdaptColors() {
        Boolean override = mOverrides.get("force_monochrome_app_icons_adapt_colors");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean gestureNavTouchInputOptimizations() {
        Boolean override = mOverrides.get("gesture_nav_touch_input_optimizations");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean hideAutomatedTasksInOverview() {
        Boolean override = mOverrides.get("hide_automated_tasks_in_overview");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean homeScreenEditImprovements() {
        Boolean override = mOverrides.get("home_screen_edit_improvements");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean ignoreThreeFingerTrackpadForNavHandleLongPress() {
        Boolean override = mOverrides.get("ignore_three_finger_trackpad_for_nav_handle_long_press");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean letterFastScroller() {
        Boolean override = mOverrides.get("letter_fast_scroller");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean modelRepository() {
        Boolean override = mOverrides.get("model_repository");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean moveToRestStateForBackgroundApp() {
        Boolean override = mOverrides.get("move_to_rest_state_for_background_app");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean msdlFeedback() {
        Boolean override = mOverrides.get("msdl_feedback");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean nudgePill() {
        Boolean override = mOverrides.get("nudge_pill");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean oneGridRotationHandling() {
        Boolean override = mOverrides.get("one_grid_rotation_handling");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean orientationFriendlyDesktopGridSpec() {
        Boolean override = mOverrides.get("orientation_friendly_desktop_grid_spec");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean privateSpaceAddFloatingMaskView() {
        Boolean override = mOverrides.get("private_space_add_floating_mask_view");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean privateSpaceAnimation() {
        Boolean override = mOverrides.get("private_space_animation");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean qsbAnimationMinorFixes() {
        Boolean override = mOverrides.get("qsb_animation_minor_fixes");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean reduceWorkspaceBlurUsage() {
        Boolean override = mOverrides.get("reduce_workspace_blur_usage");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean restoreArchivedAppIconsFromDb() {
        Boolean override = mOverrides.get("restore_archived_app_icons_from_db");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean showCreateWidgetBtnInPicker() {
        Boolean override = mOverrides.get("show_create_widget_btn_in_picker");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean showFilesOnHomeScreen() {
        Boolean override = mOverrides.get("show_files_on_home_screen");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean simplifiedLauncherModelBinding() {
        Boolean override = mOverrides.get("simplified_launcher_model_binding");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean taskbarQuietModeChangeSupport() {
        Boolean override = mOverrides.get("taskbar_quiet_mode_change_support");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean tooltipEduCombinator() {
        Boolean override = mOverrides.get("tooltip_edu_combinator");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean translateImeswitcher3ButtonsWithBubble() {
        Boolean override = mOverrides.get("translate_imeswitcher_3buttons_with_bubble");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean updateRecentsWmWwmConfiguration() {
        Boolean override = mOverrides.get("update_recents_wm_wwm_configuration");
        if (override != null) return override;
        return false;
    }

    @Override
    public boolean widgetReturnAnimationMinorFixes() {
        Boolean override = mOverrides.get("widget_return_animation_minor_fixes");
        if (override != null) return override;
        return false;
    }

}
