/* Generated by generate_flags.py - Do not edit directly */
package com.android.launcher3;

public interface FeatureFlags {
    /** All Apps will be drawn on a separate surface to improve performance. (Bug: 414847564) */
    boolean allAppsSurface();

    /** Enable background blur at app launch (Bug: 379905951) */
    boolean appLaunchBlur();

    /** Use the DisplayCutout insets to avoid intersecting with the bubble bar. (Bug: 329903073) */
    boolean avoidDisplayCutoutBubbleBar();

    /** Change model binding to use repositories instead of model callbacks (Bug: 455016031) */
    boolean bindModelUsingRepository();

    /** Enable blur in more Launcher surfaces (Bug: 444141641) */
    boolean blurOnMoreSurfaces();

    /** Launcher will be blurred when the user swipes to home. (Bug: 441691917) */
    boolean blurredHomeAnimation();

    /** Vertically centers workspace grid and drop target buttons in spring loaded state (Bug: 443995425) */
    boolean centerSpringLoadedStateVertically();

    /** Enables the condo planner experience. (Bug: 450695990) */
    boolean condoPlanner();

    /** Disables usage of blur effect for rendering automated icons (Bug: 440353845) */
    boolean disableAppAutomationBlur();

    /** Enables double tap to sleep gesture on launcher (Bug: 394952494) */
    boolean doubleTapToSleep();

    /** Enables displaying the all apps button in the hotseat. (Bug: 270393897) */
    boolean enableAllAppsButtonInHotseat();

    /** Enables all apps edu when over-swipe on the last workspace page (Bug: 441155632) */
    boolean enableAllAppsEduForOverswipe();

    /** Enable Alt + Tab KQS view to show apps in flattened structure (Bug: 382769617) */
    boolean enableAltTabKqsFlatenning();

    /** Enables indicator for active app automation in Launcher (Bug: 440353845) */
    boolean enableAppAutomationIndicator();

    /** Enables App Lock system shortcut in Launcher (Bug: 475598044) */
    boolean enableAppLockShortcut();

    /** Collapses system UI panels in response to user actions in taskbar (Bug: 492177154) */
    boolean enableCollapseSysuiPanelsOnTaskbarClick();

    /** Gate the refactor of OptionsPopupDialog to compose. (Bug: 494308318) */
    boolean enableComposeForOptionsPopupMenuDialog();

    /** Enable launcher app contrast tiles. (Bug: 341217082) */
    boolean enableContrastTiles();

    /** Enables a desktop specific layout for the cue bar. (Bug: 481800795) */
    boolean enableCueBarDesktopFormFactor();

    /** Enables mouse based workflows for interacting with launcher (Bug: 455891793) */
    boolean enableCursorDrivenWorkflows();

    /** Enables custom height for all apps on CD (Bug: 416220478) */
    boolean enableCustomHeightForAllAppsOnCd();

    /** Enables support for multi-dispatch of drag start/end events. (Bug: 456191832) */
    boolean enableDragStartEndMultiDispatch();

    /** Expand and collapse pause work button while scrolling. (Bug: 270390779) */
    boolean enableExpandingPauseWorkButton();

    /** Enables expressive folder expansion motion (Bug: 387543793) */
    boolean enableExpressiveFolderExpansion();

    /** Enables fallback recents opening inside of a window instead of an activity. (Bug: 292269949) */
    boolean enableFallbackOverviewInWindow();

    /** Enables file system folders as drop targets for other file system type items (Bug: 457783085) */
    boolean enableFileSystemFoldersAsDropTargets();

    /** Enables fixed QSB at the bottom of hotseat (Bug: 489141317) */
    boolean enableFixedQsbAtBottom();

    /** Enables focus states outline for launcher. (Bug: 310953377) */
    boolean enableFocusOutline();

    /** Enables significant refactoring for Launcher folders (Bug: 387543793) */
    boolean enableFolderRefactor();

    /** Add growth nudge in launcher (Bug: 396165728) */
    boolean enableGrowthNudge();

    /** Enables support for copy/paste of home screen files. (Bug: 482073141) */
    boolean enableHomeScreenFilesCopyPaste();

    /** Enables support for renaming home screen files. (Bug: 450710219) */
    boolean enableHomeScreenFilesRenaming();

    /** Replaces the 'Delete permanently' action with 'Move to trash' for home screen files (Bug: 424466974) */
    boolean enableHomeScreenFilesTrashing();

    /** Enables taking a new snapshot for the running task when invoking KQS (Bug: 490433482) */
    boolean enableKqsForceTakeRunningTaskThumbnail();

    /** Checks if users associated with tasks are locked later in the data flow to prevent stale data (Bug: 417220811) */
    boolean enableLaterIsLockedCheck();

    /** Enable launcher icon shape customizations (Bug: 348708061) */
    boolean enableLauncherIconShapes();

    /** Enables launcher recents opening inside of a window instead of being hosted in launcher activity. (Bug: 292269949) */
    boolean enableLauncherOverviewInWindow();

    /** Enables usage of low resolution thumbnails in preloading to save memory. (Bug: 446013310) */
    boolean enableLowResThumbnailPreloading();

    /** Changes mouse interaction behavior (Bug: 388897603) */
    boolean enableMouseInteractionChanges();

    /** Menu in Taskbar with options to launch and manage multiple instances of the same app (Bug: 355237285) */
    boolean enableMultiInstanceMenuTaskbar();

    /** Using only the most recent workspace when restoring to avoid confusion. (Bug: 325285743) */
    boolean enableNarrowGridRestore();

    /** Update touchpad gestures to match 26Q2 spec. (Bug: 460130854) */
    boolean enableNewTouchpadGestures();

    /** Enable wallpaper background for desktop tasks in overview. (Bug: 363257721) */
    boolean enableOverviewDesktopTileWallpaperBackground();

    /** Allows the user to scroll overview with a mouse click. (Bug: 443252794) */
    boolean enableOverviewPagination();

    /** Creates views for selected texts to enable accessible traversal. (Bug: 447292419) */
    boolean enableOverviewSelectTextView();

    /** Enables predictive back animation in Overview on back navigation (Bug: 421292121) */
    boolean enablePredictiveBackInOverview();

    /** Enables all Launcher features associated with private space. (Bug: 306187906) */
    boolean enablePrivateSpace();

    /** Enable Search App's widget on hotseat (Bug: 405226308) */
    boolean enableQsbOnHotseat();

    /** Enables unlock animation after device reboot (Bug: 298231234) */
    boolean enableRebootUnlockAnimation();

    /** Enable wallpaper blur for RecentsWindowManager (Bug: 402685067) */
    boolean enableRecentsWindowBlur();

    /** Enables tracking recents window logs in ProtoLog (Bug: 292269949) */
    boolean enableRecentsWindowProtoLog();

    /** Enables rewritten version of digital wellbeing toast in overview. (Bug: 404838605) */
    boolean enableRefactorDigitalWellbeingToast();

    /** Enables new workspace grid calculations method. (Bug: 302189128) */
    boolean enableResponsiveWorkspace();

    /** Enables the refactored RestoreDbTask using ModelWriter. (Bug: 489010281) */
    boolean enableRestoredbtaskModelwriterRefactor();

    /** Enables home action corner to be reversible (Bug: 416664984) */
    boolean enableReversibleHomeActionCorner();

    /** Bugfix for missing Save action in Overview Share Sheet (Bug: 493115665) */
    boolean enableSaveActionInOverviewShare();

    /** Enable more grid scale options on the launcher for desktop experience (Bug: 375491272) */
    boolean enableScalabilityForDesktopExperience();

    /** Enable Overview to launch and exit simultaneously on default and external displays wherever it was triggered or quit from (Bug: 421128035) */
    boolean enableSimultaneousOverviewTriggerOnExtendedDesktop();

    /** Enables tracking state manager logs in ProtoLog (Bug: 292269949) */
    boolean enableStateManagerProtoLog();

    /** Enable Strict Mode for the Launcher app (Bug: 394651876) */
    boolean enableStrictMode();

    /** Enables support for archived apps in Launcher3, such as empty progress bar etc. (Bug: 210590852) */
    boolean enableSupportForArchiving();

    /** Enables the magnetic detach effect to the swipe up from app gestures (Bug: 455552698) */
    boolean enableSwipeUpMagneticDetach();

    /** Enables system-level drag-and-drop (Bug: 402183121) */
    boolean enableSystemDrag();

    /** Enables system-level drag-and-drop to other apps (Bug: 440196110) */
    boolean enableSystemDragToOtherApps();

    /** Enables the 'More Options' button for accessibility features in the Taskbar (Bug: 440427169) */
    boolean enableTaskbarA11YMoreOptionsButton();

    /** Keeps taskbar behind notification shade when its pulled down (Bug: 343194358) */
    boolean enableTaskbarBehindShade();

    /** Enables taskbar customization framework. (Bug: 347281365) */
    boolean enableTaskbarCustomization();

    /** Enable dragging and dropping app icons on the taskbar. (Bug: 442605300) */
    boolean enableTaskbarDragAndDrop();

    /** Enable dragging to remove pinned apps on the taskbar. (Bug: 495823552) */
    boolean enableTaskbarDragToRemove();

    /** Enables code path that uses TaskbarIconsContainer (Bug: 437189890) */
    boolean enableTaskbarIconContainer();

    /** Enables desktop style tasakbar icon clicks, including click-to-minimize and multi-window picking. (Bug: 433770976) */
    boolean enableTaskbarIconDesktopClicks();

    /** Enables taskbar with no recreation from lifecycle changes of TaskbarActivityContext. (Bug: 299193589) */
    boolean enableTaskbarNoRecreate();

    /** Enables taskbar pinning to allow user to switch between transient and persistent taskbar flavors. (Bug: 296231746) */
    boolean enableTaskbarPinning();

    /** Enable per-window thread for taskbar (Bug: 404636836) */
    boolean enableTaskbarUiThread();

    /** Allows the user to drag and drop tasks between desktops in overview. (Bug: 434939081) */
    boolean enableTasksDragAndDropInOverview();

    /** Enables the new transactional model writer for Launcher persistence. (Bug: 457449059) */
    boolean enableTransactionalModelWriter();

    /** Enables two panel settings when on large enough displays (Bug: 204463748) */
    boolean enableTwoPaneLauncherSettings();

    /** Enables two line label inside all apps. (Bug: 270390937) */
    boolean enableTwolineAllapps();

    /** Enables visibility in home settings to see the toggle to turn on/off two lines in all apps. (Bug: 316027081) */
    boolean enableTwolineToggle();

    /** Tie unfold animation with state animation (Bug: 297057373) */
    boolean enableUnfoldStateAnimation();

    /** Enables blur in the widget picker (Bug: 436344835) */
    boolean enableWidgetPickerBlur();

    /** Enable the Widgets section in the options popup menu dialog. (Bug: 494308318) */
    boolean enableWidgetsSectionInOptionsMenu();

    /** Enables new workspace paging animation (Bug: 449196548) */
    boolean enableWorkspacePageAnimation();

    /** Enables item selection workflows in the workspace (Bug: 430287769) */
    boolean enableWorkspaceSelection();

    /** Enables folders in all apps (Bug: 341582436) */
    boolean enabledFoldersInAllApps();

    /** Enables expandable long press menu (Bug: 444003708) */
    boolean expandableLongPressMenu();

    /** Introduces a Launcher reveal animation that runs as a backup when a different process takes care of the overall transition animation. (Bug: 202516970) */
    boolean fallbackRevealAnimation();

    /** Fixes a11y issue that widgets can't be resized with single pointer (Bug: 439588493) */
    boolean fixWidgetSinglePtrResize();

    /** Search bar persists at the bottom of the screen across Launcher states (Bug: 346408388) */
    boolean floatingSearchBar();

    /** Enable the ability to generate monochromatic icons, if it is not provided by the app (Bug: 270396209) */
    boolean forceMonochromeAppIcons();

    /** Adapt colors for monochromatic icons, only valid if force_monochrome_app_icons is enabled (Bug: 418850749) */
    boolean forceMonochromeAppIconsAdaptColors();

    /** Replaces existing Gesture Nav touch input with new SpyWindow optimizations (Bug: 466226558) */
    boolean gestureNavTouchInputOptimizations();

    /** Hide a task from overview if it is being automated. (Bug: 440355882) */
    boolean hideAutomatedTasksInOverview();

    /** Improves item removal and resizing within home screen (Bug: 416087474) */
    boolean homeScreenEditImprovements();

    /** Ignore three finger trackpad event for nav handle long press (Bug: 342143522) */
    boolean ignoreThreeFingerTrackpadForNavHandleLongPress();

    /** Change fast scroller to a lettered list (Bug: 358673724) */
    boolean letterFastScroller();

    /** Adds various data repositories for the model (Bug: 390572144) */
    boolean modelRepository();

    /** Move launcher to rest state if it is in background app state when starting back animation (Bug: 469834354) */
    boolean moveToRestStateForBackgroundApp();

    /** Enable MSDL feedback for Launcher interactions (Bug: 377496684) */
    boolean msdlFeedback();

    /** This flag enables change the nav or 3 button to nudge related edu (pill or icon) for CtS. (Bug: 409121556) */
    boolean nudgePill();

    /** New landscape approach for the workspace using different rows and columns in landscape and portrait (Bug: 364711814) */
    boolean oneGridRotationHandling();

    /** Uses a desktop grid spec that specifies grid dimensions that look reasonably well when the device is used in portrait mode (Bug: 444244391) */
    boolean orientationFriendlyDesktopGridSpec();

    /** This flag enables the floating mask view as part of the Private Space animation. (Bug: 339850589) */
    boolean privateSpaceAddFloatingMaskView();

    /** This flag enables the animation of the Private Space container (Bug: 299294792) */
    boolean privateSpaceAnimation();

    /** Fixed return animation for QSB. Did some minor tweaks for improving the animation. (Bug: 453966496) */
    boolean qsbAnimationMinorFixes();

    /** Disables the full workspace blur and zoom effects behind surfaces like the \ (Bug: 455987559) */
    boolean reduceWorkspaceBlurUsage();

    /** Restores pre-archived icons from db when available, mimicing promise icons (Bug: 391913214) */
    boolean restoreArchivedAppIconsFromDb();

    /** Shows create widget button in widget picker (Bug: 459260964) */
    boolean showCreateWidgetBtnInPicker();

    /** Enables file and folder items on the home screen (Bug: 375644352) */
    boolean showFilesOnHomeScreen();

    /** Simplified approach to binding launcher model asynchronously (Bug: 448982751) */
    boolean simplifiedLauncherModelBinding();

    /** Support changing quiet mode for user profiles in taskbar. (Bug: 345760034) */
    boolean taskbarQuietModeChangeSupport();

    /** Separate logic of education tooltip combination from presentation (Bug: 444693509) */
    boolean tooltipEduCombinator();

    /** Translate the IME Switcher when 3-buttons Navigation with Bubble Icon (Bug: 494111189) */
    boolean translateImeswitcher3ButtonsWithBubble();

    /** Bugfix for missing configurations in RWM (Bug: 448688934) */
    boolean updateRecentsWmWwmConfiguration();

    /** Fixed return animation for launcher widgets. Did some minor tweaks for improving the animation. (Bug: 453966496) */
    boolean widgetReturnAnimationMinorFixes();

}
