/* Generated by generate_flags.py - Do not edit directly */
package com.android.launcher3;

public final class Flags {
    private static FeatureFlags sFeatureFlags = new FeatureFlagsImpl();

    private Flags() {}

    public static void setFeatureFlags(FeatureFlags flags) {
        sFeatureFlags = flags;
    }

    public static final String FLAG_ALL_APPS_SURFACE = "com.android.launcher3.all_apps_surface";
    /** All Apps will be drawn on a separate surface to improve performance. */
    public static boolean allAppsSurface() {
        return sFeatureFlags.allAppsSurface();
    }

    public static final String FLAG_APP_LAUNCH_BLUR = "com.android.launcher3.app_launch_blur";
    /** Enable background blur at app launch */
    public static boolean appLaunchBlur() {
        return sFeatureFlags.appLaunchBlur();
    }

    public static final String FLAG_AVOID_DISPLAY_CUTOUT_BUBBLE_BAR = "com.android.launcher3.avoid_display_cutout_bubble_bar";
    /** Use the DisplayCutout insets to avoid intersecting with the bubble bar. */
    public static boolean avoidDisplayCutoutBubbleBar() {
        return sFeatureFlags.avoidDisplayCutoutBubbleBar();
    }

    public static final String FLAG_BIND_MODEL_USING_REPOSITORY = "com.android.launcher3.bind_model_using_repository";
    /** Change model binding to use repositories instead of model callbacks */
    public static boolean bindModelUsingRepository() {
        return sFeatureFlags.bindModelUsingRepository();
    }

    public static final String FLAG_BLUR_ON_MORE_SURFACES = "com.android.launcher3.blur_on_more_surfaces";
    /** Enable blur in more Launcher surfaces */
    public static boolean blurOnMoreSurfaces() {
        return sFeatureFlags.blurOnMoreSurfaces();
    }

    public static final String FLAG_BLURRED_HOME_ANIMATION = "com.android.launcher3.blurred_home_animation";
    /** Launcher will be blurred when the user swipes to home. */
    public static boolean blurredHomeAnimation() {
        return sFeatureFlags.blurredHomeAnimation();
    }

    public static final String FLAG_CENTER_SPRING_LOADED_STATE_VERTICALLY = "com.android.launcher3.center_spring_loaded_state_vertically";
    /** Vertically centers workspace grid and drop target buttons in spring loaded state */
    public static boolean centerSpringLoadedStateVertically() {
        return sFeatureFlags.centerSpringLoadedStateVertically();
    }

    public static final String FLAG_CONDO_PLANNER = "com.android.launcher3.condo_planner";
    /** Enables the condo planner experience. */
    public static boolean condoPlanner() {
        return sFeatureFlags.condoPlanner();
    }

    public static final String FLAG_DISABLE_APP_AUTOMATION_BLUR = "com.android.launcher3.disable_app_automation_blur";
    /** Disables usage of blur effect for rendering automated icons */
    public static boolean disableAppAutomationBlur() {
        return sFeatureFlags.disableAppAutomationBlur();
    }

    public static final String FLAG_DOUBLE_TAP_TO_SLEEP = "com.android.launcher3.double_tap_to_sleep";
    /** Enables double tap to sleep gesture on launcher */
    public static boolean doubleTapToSleep() {
        return sFeatureFlags.doubleTapToSleep();
    }

    public static final String FLAG_ENABLE_ALL_APPS_BUTTON_IN_HOTSEAT = "com.android.launcher3.enable_all_apps_button_in_hotseat";
    /** Enables displaying the all apps button in the hotseat. */
    public static boolean enableAllAppsButtonInHotseat() {
        return sFeatureFlags.enableAllAppsButtonInHotseat();
    }

    public static final String FLAG_ENABLE_ALL_APPS_EDU_FOR_OVERSWIPE = "com.android.launcher3.enable_all_apps_edu_for_overswipe";
    /** Enables all apps edu when over-swipe on the last workspace page */
    public static boolean enableAllAppsEduForOverswipe() {
        return sFeatureFlags.enableAllAppsEduForOverswipe();
    }

    public static final String FLAG_ENABLE_ALT_TAB_KQS_FLATENNING = "com.android.launcher3.enable_alt_tab_kqs_flatenning";
    /** Enable Alt + Tab KQS view to show apps in flattened structure */
    public static boolean enableAltTabKqsFlatenning() {
        return sFeatureFlags.enableAltTabKqsFlatenning();
    }

    public static final String FLAG_ENABLE_APP_AUTOMATION_INDICATOR = "com.android.launcher3.enable_app_automation_indicator";
    /** Enables indicator for active app automation in Launcher */
    public static boolean enableAppAutomationIndicator() {
        return sFeatureFlags.enableAppAutomationIndicator();
    }

    public static final String FLAG_ENABLE_APP_LOCK_SHORTCUT = "com.android.launcher3.enable_app_lock_shortcut";
    /** Enables App Lock system shortcut in Launcher */
    public static boolean enableAppLockShortcut() {
        return sFeatureFlags.enableAppLockShortcut();
    }

    public static final String FLAG_ENABLE_COLLAPSE_SYSUI_PANELS_ON_TASKBAR_CLICK = "com.android.launcher3.enable_collapse_sysui_panels_on_taskbar_click";
    /** Collapses system UI panels in response to user actions in taskbar */
    public static boolean enableCollapseSysuiPanelsOnTaskbarClick() {
        return sFeatureFlags.enableCollapseSysuiPanelsOnTaskbarClick();
    }

    public static final String FLAG_ENABLE_COMPOSE_FOR_OPTIONS_POPUP_MENU_DIALOG = "com.android.launcher3.enable_compose_for_options_popup_menu_dialog";
    /** Gate the refactor of OptionsPopupDialog to compose. */
    public static boolean enableComposeForOptionsPopupMenuDialog() {
        return sFeatureFlags.enableComposeForOptionsPopupMenuDialog();
    }

    public static final String FLAG_ENABLE_CONTRAST_TILES = "com.android.launcher3.enable_contrast_tiles";
    /** Enable launcher app contrast tiles. */
    public static boolean enableContrastTiles() {
        return sFeatureFlags.enableContrastTiles();
    }

    public static final String FLAG_ENABLE_CUE_BAR_DESKTOP_FORM_FACTOR = "com.android.launcher3.enable_cue_bar_desktop_form_factor";
    /** Enables a desktop specific layout for the cue bar. */
    public static boolean enableCueBarDesktopFormFactor() {
        return sFeatureFlags.enableCueBarDesktopFormFactor();
    }

    public static final String FLAG_ENABLE_CURSOR_DRIVEN_WORKFLOWS = "com.android.launcher3.enable_cursor_driven_workflows";
    /** Enables mouse based workflows for interacting with launcher */
    public static boolean enableCursorDrivenWorkflows() {
        return sFeatureFlags.enableCursorDrivenWorkflows();
    }

    public static final String FLAG_ENABLE_CUSTOM_HEIGHT_FOR_ALL_APPS_ON_CD = "com.android.launcher3.enable_custom_height_for_all_apps_on_cd";
    /** Enables custom height for all apps on CD */
    public static boolean enableCustomHeightForAllAppsOnCd() {
        return sFeatureFlags.enableCustomHeightForAllAppsOnCd();
    }

    public static final String FLAG_ENABLE_DRAG_START_END_MULTI_DISPATCH = "com.android.launcher3.enable_drag_start_end_multi_dispatch";
    /** Enables support for multi-dispatch of drag start/end events. */
    public static boolean enableDragStartEndMultiDispatch() {
        return sFeatureFlags.enableDragStartEndMultiDispatch();
    }

    public static final String FLAG_ENABLE_EXPANDING_PAUSE_WORK_BUTTON = "com.android.launcher3.enable_expanding_pause_work_button";
    /** Expand and collapse pause work button while scrolling. */
    public static boolean enableExpandingPauseWorkButton() {
        return sFeatureFlags.enableExpandingPauseWorkButton();
    }

    public static final String FLAG_ENABLE_EXPRESSIVE_FOLDER_EXPANSION = "com.android.launcher3.enable_expressive_folder_expansion";
    /** Enables expressive folder expansion motion */
    public static boolean enableExpressiveFolderExpansion() {
        return sFeatureFlags.enableExpressiveFolderExpansion();
    }

    public static final String FLAG_ENABLE_FALLBACK_OVERVIEW_IN_WINDOW = "com.android.launcher3.enable_fallback_overview_in_window";
    /** Enables fallback recents opening inside of a window instead of an activity. */
    public static boolean enableFallbackOverviewInWindow() {
        return sFeatureFlags.enableFallbackOverviewInWindow();
    }

    public static final String FLAG_ENABLE_FILE_SYSTEM_FOLDERS_AS_DROP_TARGETS = "com.android.launcher3.enable_file_system_folders_as_drop_targets";
    /** Enables file system folders as drop targets for other file system type items */
    public static boolean enableFileSystemFoldersAsDropTargets() {
        return sFeatureFlags.enableFileSystemFoldersAsDropTargets();
    }

    public static final String FLAG_ENABLE_FIXED_QSB_AT_BOTTOM = "com.android.launcher3.enable_fixed_qsb_at_bottom";
    /** Enables fixed QSB at the bottom of hotseat */
    public static boolean enableFixedQsbAtBottom() {
        return sFeatureFlags.enableFixedQsbAtBottom();
    }

    public static final String FLAG_ENABLE_FOCUS_OUTLINE = "com.android.launcher3.enable_focus_outline";
    /** Enables focus states outline for launcher. */
    public static boolean enableFocusOutline() {
        return sFeatureFlags.enableFocusOutline();
    }

    public static final String FLAG_ENABLE_FOLDER_REFACTOR = "com.android.launcher3.enable_folder_refactor";
    /** Enables significant refactoring for Launcher folders */
    public static boolean enableFolderRefactor() {
        return sFeatureFlags.enableFolderRefactor();
    }

    public static final String FLAG_ENABLE_GROWTH_NUDGE = "com.android.launcher3.enable_growth_nudge";
    /** Add growth nudge in launcher */
    public static boolean enableGrowthNudge() {
        return sFeatureFlags.enableGrowthNudge();
    }

    public static final String FLAG_ENABLE_HOME_SCREEN_FILES_COPY_PASTE = "com.android.launcher3.enable_home_screen_files_copy_paste";
    /** Enables support for copy/paste of home screen files. */
    public static boolean enableHomeScreenFilesCopyPaste() {
        return sFeatureFlags.enableHomeScreenFilesCopyPaste();
    }

    public static final String FLAG_ENABLE_HOME_SCREEN_FILES_RENAMING = "com.android.launcher3.enable_home_screen_files_renaming";
    /** Enables support for renaming home screen files. */
    public static boolean enableHomeScreenFilesRenaming() {
        return sFeatureFlags.enableHomeScreenFilesRenaming();
    }

    public static final String FLAG_ENABLE_HOME_SCREEN_FILES_TRASHING = "com.android.launcher3.enable_home_screen_files_trashing";
    /** Replaces the 'Delete permanently' action with 'Move to trash' for home screen files */
    public static boolean enableHomeScreenFilesTrashing() {
        return sFeatureFlags.enableHomeScreenFilesTrashing();
    }

    public static final String FLAG_ENABLE_KQS_FORCE_TAKE_RUNNING_TASK_THUMBNAIL = "com.android.launcher3.enable_kqs_force_take_running_task_thumbnail";
    /** Enables taking a new snapshot for the running task when invoking KQS */
    public static boolean enableKqsForceTakeRunningTaskThumbnail() {
        return sFeatureFlags.enableKqsForceTakeRunningTaskThumbnail();
    }

    public static final String FLAG_ENABLE_LATER_IS_LOCKED_CHECK = "com.android.launcher3.enable_later_is_locked_check";
    /** Checks if users associated with tasks are locked later in the data flow to prevent stale data */
    public static boolean enableLaterIsLockedCheck() {
        return sFeatureFlags.enableLaterIsLockedCheck();
    }

    public static final String FLAG_ENABLE_LAUNCHER_ICON_SHAPES = "com.android.launcher3.enable_launcher_icon_shapes";
    /** Enable launcher icon shape customizations */
    public static boolean enableLauncherIconShapes() {
        return sFeatureFlags.enableLauncherIconShapes();
    }

    public static final String FLAG_ENABLE_LAUNCHER_OVERVIEW_IN_WINDOW = "com.android.launcher3.enable_launcher_overview_in_window";
    /** Enables launcher recents opening inside of a window instead of being hosted in launcher activity. */
    public static boolean enableLauncherOverviewInWindow() {
        return sFeatureFlags.enableLauncherOverviewInWindow();
    }

    public static final String FLAG_ENABLE_LOW_RES_THUMBNAIL_PRELOADING = "com.android.launcher3.enable_low_res_thumbnail_preloading";
    /** Enables usage of low resolution thumbnails in preloading to save memory. */
    public static boolean enableLowResThumbnailPreloading() {
        return sFeatureFlags.enableLowResThumbnailPreloading();
    }

    public static final String FLAG_ENABLE_MOUSE_INTERACTION_CHANGES = "com.android.launcher3.enable_mouse_interaction_changes";
    /** Changes mouse interaction behavior */
    public static boolean enableMouseInteractionChanges() {
        return sFeatureFlags.enableMouseInteractionChanges();
    }

    public static final String FLAG_ENABLE_MULTI_INSTANCE_MENU_TASKBAR = "com.android.launcher3.enable_multi_instance_menu_taskbar";
    /** Menu in Taskbar with options to launch and manage multiple instances of the same app */
    public static boolean enableMultiInstanceMenuTaskbar() {
        return sFeatureFlags.enableMultiInstanceMenuTaskbar();
    }

    public static final String FLAG_ENABLE_NARROW_GRID_RESTORE = "com.android.launcher3.enable_narrow_grid_restore";
    /** Using only the most recent workspace when restoring to avoid confusion. */
    public static boolean enableNarrowGridRestore() {
        return sFeatureFlags.enableNarrowGridRestore();
    }

    public static final String FLAG_ENABLE_NEW_TOUCHPAD_GESTURES = "com.android.launcher3.enable_new_touchpad_gestures";
    /** Update touchpad gestures to match 26Q2 spec. */
    public static boolean enableNewTouchpadGestures() {
        return sFeatureFlags.enableNewTouchpadGestures();
    }

    public static final String FLAG_ENABLE_OVERVIEW_DESKTOP_TILE_WALLPAPER_BACKGROUND = "com.android.launcher3.enable_overview_desktop_tile_wallpaper_background";
    /** Enable wallpaper background for desktop tasks in overview. */
    public static boolean enableOverviewDesktopTileWallpaperBackground() {
        return sFeatureFlags.enableOverviewDesktopTileWallpaperBackground();
    }

    public static final String FLAG_ENABLE_OVERVIEW_PAGINATION = "com.android.launcher3.enable_overview_pagination";
    /** Allows the user to scroll overview with a mouse click. */
    public static boolean enableOverviewPagination() {
        return sFeatureFlags.enableOverviewPagination();
    }

    public static final String FLAG_ENABLE_OVERVIEW_SELECT_TEXT_VIEW = "com.android.launcher3.enable_overview_select_text_view";
    /** Creates views for selected texts to enable accessible traversal. */
    public static boolean enableOverviewSelectTextView() {
        return sFeatureFlags.enableOverviewSelectTextView();
    }

    public static final String FLAG_ENABLE_PREDICTIVE_BACK_IN_OVERVIEW = "com.android.launcher3.enable_predictive_back_in_overview";
    /** Enables predictive back animation in Overview on back navigation */
    public static boolean enablePredictiveBackInOverview() {
        return sFeatureFlags.enablePredictiveBackInOverview();
    }

    public static final String FLAG_ENABLE_PRIVATE_SPACE = "com.android.launcher3.enable_private_space";
    /** Enables all Launcher features associated with private space. */
    public static boolean enablePrivateSpace() {
        return sFeatureFlags.enablePrivateSpace();
    }

    public static final String FLAG_ENABLE_QSB_ON_HOTSEAT = "com.android.launcher3.enable_qsb_on_hotseat";
    /** Enable Search App's widget on hotseat */
    public static boolean enableQsbOnHotseat() {
        return sFeatureFlags.enableQsbOnHotseat();
    }

    public static final String FLAG_ENABLE_REBOOT_UNLOCK_ANIMATION = "com.android.launcher3.enable_reboot_unlock_animation";
    /** Enables unlock animation after device reboot */
    public static boolean enableRebootUnlockAnimation() {
        return sFeatureFlags.enableRebootUnlockAnimation();
    }

    public static final String FLAG_ENABLE_RECENTS_WINDOW_BLUR = "com.android.launcher3.enable_recents_window_blur";
    /** Enable wallpaper blur for RecentsWindowManager */
    public static boolean enableRecentsWindowBlur() {
        return sFeatureFlags.enableRecentsWindowBlur();
    }

    public static final String FLAG_ENABLE_RECENTS_WINDOW_PROTO_LOG = "com.android.launcher3.enable_recents_window_proto_log";
    /** Enables tracking recents window logs in ProtoLog */
    public static boolean enableRecentsWindowProtoLog() {
        return sFeatureFlags.enableRecentsWindowProtoLog();
    }

    public static final String FLAG_ENABLE_REFACTOR_DIGITAL_WELLBEING_TOAST = "com.android.launcher3.enable_refactor_digital_wellbeing_toast";
    /** Enables rewritten version of digital wellbeing toast in overview. */
    public static boolean enableRefactorDigitalWellbeingToast() {
        return sFeatureFlags.enableRefactorDigitalWellbeingToast();
    }

    public static final String FLAG_ENABLE_RESPONSIVE_WORKSPACE = "com.android.launcher3.enable_responsive_workspace";
    /** Enables new workspace grid calculations method. */
    public static boolean enableResponsiveWorkspace() {
        return sFeatureFlags.enableResponsiveWorkspace();
    }

    public static final String FLAG_ENABLE_RESTOREDBTASK_MODELWRITER_REFACTOR = "com.android.launcher3.enable_restoredbtask_modelwriter_refactor";
    /** Enables the refactored RestoreDbTask using ModelWriter. */
    public static boolean enableRestoredbtaskModelwriterRefactor() {
        return sFeatureFlags.enableRestoredbtaskModelwriterRefactor();
    }

    public static final String FLAG_ENABLE_REVERSIBLE_HOME_ACTION_CORNER = "com.android.launcher3.enable_reversible_home_action_corner";
    /** Enables home action corner to be reversible */
    public static boolean enableReversibleHomeActionCorner() {
        return sFeatureFlags.enableReversibleHomeActionCorner();
    }

    public static final String FLAG_ENABLE_SAVE_ACTION_IN_OVERVIEW_SHARE = "com.android.launcher3.enable_save_action_in_overview_share";
    /** Bugfix for missing Save action in Overview Share Sheet */
    public static boolean enableSaveActionInOverviewShare() {
        return sFeatureFlags.enableSaveActionInOverviewShare();
    }

    public static final String FLAG_ENABLE_SCALABILITY_FOR_DESKTOP_EXPERIENCE = "com.android.launcher3.enable_scalability_for_desktop_experience";
    /** Enable more grid scale options on the launcher for desktop experience */
    public static boolean enableScalabilityForDesktopExperience() {
        return sFeatureFlags.enableScalabilityForDesktopExperience();
    }

    public static final String FLAG_ENABLE_SIMULTANEOUS_OVERVIEW_TRIGGER_ON_EXTENDED_DESKTOP = "com.android.launcher3.enable_simultaneous_overview_trigger_on_extended_desktop";
    /** Enable Overview to launch and exit simultaneously on default and external displays wherever it was triggered or quit from */
    public static boolean enableSimultaneousOverviewTriggerOnExtendedDesktop() {
        return sFeatureFlags.enableSimultaneousOverviewTriggerOnExtendedDesktop();
    }

    public static final String FLAG_ENABLE_STATE_MANAGER_PROTO_LOG = "com.android.launcher3.enable_state_manager_proto_log";
    /** Enables tracking state manager logs in ProtoLog */
    public static boolean enableStateManagerProtoLog() {
        return sFeatureFlags.enableStateManagerProtoLog();
    }

    public static final String FLAG_ENABLE_STRICT_MODE = "com.android.launcher3.enable_strict_mode";
    /** Enable Strict Mode for the Launcher app */
    public static boolean enableStrictMode() {
        return sFeatureFlags.enableStrictMode();
    }

    public static final String FLAG_ENABLE_SUPPORT_FOR_ARCHIVING = "com.android.launcher3.enable_support_for_archiving";
    /** Enables support for archived apps in Launcher3, such as empty progress bar etc. */
    public static boolean enableSupportForArchiving() {
        return sFeatureFlags.enableSupportForArchiving();
    }

    public static final String FLAG_ENABLE_SWIPE_UP_MAGNETIC_DETACH = "com.android.launcher3.enable_swipe_up_magnetic_detach";
    /** Enables the magnetic detach effect to the swipe up from app gestures */
    public static boolean enableSwipeUpMagneticDetach() {
        return sFeatureFlags.enableSwipeUpMagneticDetach();
    }

    public static final String FLAG_ENABLE_SYSTEM_DRAG = "com.android.launcher3.enable_system_drag";
    /** Enables system-level drag-and-drop */
    public static boolean enableSystemDrag() {
        return sFeatureFlags.enableSystemDrag();
    }

    public static final String FLAG_ENABLE_SYSTEM_DRAG_TO_OTHER_APPS = "com.android.launcher3.enable_system_drag_to_other_apps";
    /** Enables system-level drag-and-drop to other apps */
    public static boolean enableSystemDragToOtherApps() {
        return sFeatureFlags.enableSystemDragToOtherApps();
    }

    public static final String FLAG_ENABLE_TASKBAR_A11Y_MORE_OPTIONS_BUTTON = "com.android.launcher3.enable_taskbar_a11y_more_options_button";
    /** Enables the 'More Options' button for accessibility features in the Taskbar */
    public static boolean enableTaskbarA11YMoreOptionsButton() {
        return sFeatureFlags.enableTaskbarA11YMoreOptionsButton();
    }

    public static final String FLAG_ENABLE_TASKBAR_BEHIND_SHADE = "com.android.launcher3.enable_taskbar_behind_shade";
    /** Keeps taskbar behind notification shade when its pulled down */
    public static boolean enableTaskbarBehindShade() {
        return sFeatureFlags.enableTaskbarBehindShade();
    }

    public static final String FLAG_ENABLE_TASKBAR_CUSTOMIZATION = "com.android.launcher3.enable_taskbar_customization";
    /** Enables taskbar customization framework. */
    public static boolean enableTaskbarCustomization() {
        return sFeatureFlags.enableTaskbarCustomization();
    }

    public static final String FLAG_ENABLE_TASKBAR_DRAG_AND_DROP = "com.android.launcher3.enable_taskbar_drag_and_drop";
    /** Enable dragging and dropping app icons on the taskbar. */
    public static boolean enableTaskbarDragAndDrop() {
        return sFeatureFlags.enableTaskbarDragAndDrop();
    }

    public static final String FLAG_ENABLE_TASKBAR_DRAG_TO_REMOVE = "com.android.launcher3.enable_taskbar_drag_to_remove";
    /** Enable dragging to remove pinned apps on the taskbar. */
    public static boolean enableTaskbarDragToRemove() {
        return sFeatureFlags.enableTaskbarDragToRemove();
    }

    public static final String FLAG_ENABLE_TASKBAR_ICON_CONTAINER = "com.android.launcher3.enable_taskbar_icon_container";
    /** Enables code path that uses TaskbarIconsContainer */
    public static boolean enableTaskbarIconContainer() {
        return sFeatureFlags.enableTaskbarIconContainer();
    }

    public static final String FLAG_ENABLE_TASKBAR_ICON_DESKTOP_CLICKS = "com.android.launcher3.enable_taskbar_icon_desktop_clicks";
    /** Enables desktop style tasakbar icon clicks, including click-to-minimize and multi-window picking. */
    public static boolean enableTaskbarIconDesktopClicks() {
        return sFeatureFlags.enableTaskbarIconDesktopClicks();
    }

    public static final String FLAG_ENABLE_TASKBAR_NO_RECREATE = "com.android.launcher3.enable_taskbar_no_recreate";
    /** Enables taskbar with no recreation from lifecycle changes of TaskbarActivityContext. */
    public static boolean enableTaskbarNoRecreate() {
        return sFeatureFlags.enableTaskbarNoRecreate();
    }

    public static final String FLAG_ENABLE_TASKBAR_PINNING = "com.android.launcher3.enable_taskbar_pinning";
    /** Enables taskbar pinning to allow user to switch between transient and persistent taskbar flavors. */
    public static boolean enableTaskbarPinning() {
        return sFeatureFlags.enableTaskbarPinning();
    }

    public static final String FLAG_ENABLE_TASKBAR_UI_THREAD = "com.android.launcher3.enable_taskbar_ui_thread";
    /** Enable per-window thread for taskbar */
    public static boolean enableTaskbarUiThread() {
        return sFeatureFlags.enableTaskbarUiThread();
    }

    public static final String FLAG_ENABLE_TASKS_DRAG_AND_DROP_IN_OVERVIEW = "com.android.launcher3.enable_tasks_drag_and_drop_in_overview";
    /** Allows the user to drag and drop tasks between desktops in overview. */
    public static boolean enableTasksDragAndDropInOverview() {
        return sFeatureFlags.enableTasksDragAndDropInOverview();
    }

    public static final String FLAG_ENABLE_TRANSACTIONAL_MODEL_WRITER = "com.android.launcher3.enable_transactional_model_writer";
    /** Enables the new transactional model writer for Launcher persistence. */
    public static boolean enableTransactionalModelWriter() {
        return sFeatureFlags.enableTransactionalModelWriter();
    }

    public static final String FLAG_ENABLE_TWO_PANE_LAUNCHER_SETTINGS = "com.android.launcher3.enable_two_pane_launcher_settings";
    /** Enables two panel settings when on large enough displays */
    public static boolean enableTwoPaneLauncherSettings() {
        return sFeatureFlags.enableTwoPaneLauncherSettings();
    }

    public static final String FLAG_ENABLE_TWOLINE_ALLAPPS = "com.android.launcher3.enable_twoline_allapps";
    /** Enables two line label inside all apps. */
    public static boolean enableTwolineAllapps() {
        return sFeatureFlags.enableTwolineAllapps();
    }

    public static final String FLAG_ENABLE_TWOLINE_TOGGLE = "com.android.launcher3.enable_twoline_toggle";
    /** Enables visibility in home settings to see the toggle to turn on/off two lines in all apps. */
    public static boolean enableTwolineToggle() {
        return sFeatureFlags.enableTwolineToggle();
    }

    public static final String FLAG_ENABLE_UNFOLD_STATE_ANIMATION = "com.android.launcher3.enable_unfold_state_animation";
    /** Tie unfold animation with state animation */
    public static boolean enableUnfoldStateAnimation() {
        return sFeatureFlags.enableUnfoldStateAnimation();
    }

    public static final String FLAG_ENABLE_WIDGET_PICKER_BLUR = "com.android.launcher3.enable_widget_picker_blur";
    /** Enables blur in the widget picker */
    public static boolean enableWidgetPickerBlur() {
        return sFeatureFlags.enableWidgetPickerBlur();
    }

    public static final String FLAG_ENABLE_WIDGETS_SECTION_IN_OPTIONS_MENU = "com.android.launcher3.enable_widgets_section_in_options_menu";
    /** Enable the Widgets section in the options popup menu dialog. */
    public static boolean enableWidgetsSectionInOptionsMenu() {
        return sFeatureFlags.enableWidgetsSectionInOptionsMenu();
    }

    public static final String FLAG_ENABLE_WORKSPACE_PAGE_ANIMATION = "com.android.launcher3.enable_workspace_page_animation";
    /** Enables new workspace paging animation */
    public static boolean enableWorkspacePageAnimation() {
        return sFeatureFlags.enableWorkspacePageAnimation();
    }

    public static final String FLAG_ENABLE_WORKSPACE_SELECTION = "com.android.launcher3.enable_workspace_selection";
    /** Enables item selection workflows in the workspace */
    public static boolean enableWorkspaceSelection() {
        return sFeatureFlags.enableWorkspaceSelection();
    }

    public static final String FLAG_ENABLED_FOLDERS_IN_ALL_APPS = "com.android.launcher3.enabled_folders_in_all_apps";
    /** Enables folders in all apps */
    public static boolean enabledFoldersInAllApps() {
        return sFeatureFlags.enabledFoldersInAllApps();
    }

    public static final String FLAG_EXPANDABLE_LONG_PRESS_MENU = "com.android.launcher3.expandable_long_press_menu";
    /** Enables expandable long press menu */
    public static boolean expandableLongPressMenu() {
        return sFeatureFlags.expandableLongPressMenu();
    }

    public static final String FLAG_FALLBACK_REVEAL_ANIMATION = "com.android.launcher3.fallback_reveal_animation";
    /** Introduces a Launcher reveal animation that runs as a backup when a different process takes care of the overall transition animation. */
    public static boolean fallbackRevealAnimation() {
        return sFeatureFlags.fallbackRevealAnimation();
    }

    public static final String FLAG_FIX_WIDGET_SINGLE_PTR_RESIZE = "com.android.launcher3.fix_widget_single_ptr_resize";
    /** Fixes a11y issue that widgets can't be resized with single pointer */
    public static boolean fixWidgetSinglePtrResize() {
        return sFeatureFlags.fixWidgetSinglePtrResize();
    }

    public static final String FLAG_FLOATING_SEARCH_BAR = "com.android.launcher3.floating_search_bar";
    /** Search bar persists at the bottom of the screen across Launcher states */
    public static boolean floatingSearchBar() {
        return sFeatureFlags.floatingSearchBar();
    }

    public static final String FLAG_FORCE_MONOCHROME_APP_ICONS = "com.android.launcher3.force_monochrome_app_icons";
    /** Enable the ability to generate monochromatic icons, if it is not provided by the app */
    public static boolean forceMonochromeAppIcons() {
        return sFeatureFlags.forceMonochromeAppIcons();
    }

    public static final String FLAG_FORCE_MONOCHROME_APP_ICONS_ADAPT_COLORS = "com.android.launcher3.force_monochrome_app_icons_adapt_colors";
    /** Adapt colors for monochromatic icons, only valid if force_monochrome_app_icons is enabled */
    public static boolean forceMonochromeAppIconsAdaptColors() {
        return sFeatureFlags.forceMonochromeAppIconsAdaptColors();
    }

    public static final String FLAG_GESTURE_NAV_TOUCH_INPUT_OPTIMIZATIONS = "com.android.launcher3.gesture_nav_touch_input_optimizations";
    /** Replaces existing Gesture Nav touch input with new SpyWindow optimizations */
    public static boolean gestureNavTouchInputOptimizations() {
        return sFeatureFlags.gestureNavTouchInputOptimizations();
    }

    public static final String FLAG_HIDE_AUTOMATED_TASKS_IN_OVERVIEW = "com.android.launcher3.hide_automated_tasks_in_overview";
    /** Hide a task from overview if it is being automated. */
    public static boolean hideAutomatedTasksInOverview() {
        return sFeatureFlags.hideAutomatedTasksInOverview();
    }

    public static final String FLAG_HOME_SCREEN_EDIT_IMPROVEMENTS = "com.android.launcher3.home_screen_edit_improvements";
    /** Improves item removal and resizing within home screen */
    public static boolean homeScreenEditImprovements() {
        return sFeatureFlags.homeScreenEditImprovements();
    }

    public static final String FLAG_IGNORE_THREE_FINGER_TRACKPAD_FOR_NAV_HANDLE_LONG_PRESS = "com.android.launcher3.ignore_three_finger_trackpad_for_nav_handle_long_press";
    /** Ignore three finger trackpad event for nav handle long press */
    public static boolean ignoreThreeFingerTrackpadForNavHandleLongPress() {
        return sFeatureFlags.ignoreThreeFingerTrackpadForNavHandleLongPress();
    }

    public static final String FLAG_LETTER_FAST_SCROLLER = "com.android.launcher3.letter_fast_scroller";
    /** Change fast scroller to a lettered list */
    public static boolean letterFastScroller() {
        return sFeatureFlags.letterFastScroller();
    }

    public static final String FLAG_MODEL_REPOSITORY = "com.android.launcher3.model_repository";
    /** Adds various data repositories for the model */
    public static boolean modelRepository() {
        return sFeatureFlags.modelRepository();
    }

    public static final String FLAG_MOVE_TO_REST_STATE_FOR_BACKGROUND_APP = "com.android.launcher3.move_to_rest_state_for_background_app";
    /** Move launcher to rest state if it is in background app state when starting back animation */
    public static boolean moveToRestStateForBackgroundApp() {
        return sFeatureFlags.moveToRestStateForBackgroundApp();
    }

    public static final String FLAG_MSDL_FEEDBACK = "com.android.launcher3.msdl_feedback";
    /** Enable MSDL feedback for Launcher interactions */
    public static boolean msdlFeedback() {
        return sFeatureFlags.msdlFeedback();
    }

    public static final String FLAG_NUDGE_PILL = "com.android.launcher3.nudge_pill";
    /** This flag enables change the nav or 3 button to nudge related edu (pill or icon) for CtS. */
    public static boolean nudgePill() {
        return sFeatureFlags.nudgePill();
    }

    public static final String FLAG_ONE_GRID_ROTATION_HANDLING = "com.android.launcher3.one_grid_rotation_handling";
    /** New landscape approach for the workspace using different rows and columns in landscape and portrait */
    public static boolean oneGridRotationHandling() {
        return sFeatureFlags.oneGridRotationHandling();
    }

    public static final String FLAG_ORIENTATION_FRIENDLY_DESKTOP_GRID_SPEC = "com.android.launcher3.orientation_friendly_desktop_grid_spec";
    /** Uses a desktop grid spec that specifies grid dimensions that look reasonably well when the device is used in portrait mode */
    public static boolean orientationFriendlyDesktopGridSpec() {
        return sFeatureFlags.orientationFriendlyDesktopGridSpec();
    }

    public static final String FLAG_PRIVATE_SPACE_ADD_FLOATING_MASK_VIEW = "com.android.launcher3.private_space_add_floating_mask_view";
    /** This flag enables the floating mask view as part of the Private Space animation. */
    public static boolean privateSpaceAddFloatingMaskView() {
        return sFeatureFlags.privateSpaceAddFloatingMaskView();
    }

    public static final String FLAG_PRIVATE_SPACE_ANIMATION = "com.android.launcher3.private_space_animation";
    /** This flag enables the animation of the Private Space container */
    public static boolean privateSpaceAnimation() {
        return sFeatureFlags.privateSpaceAnimation();
    }

    public static final String FLAG_QSB_ANIMATION_MINOR_FIXES = "com.android.launcher3.qsb_animation_minor_fixes";
    /** Fixed return animation for QSB. Did some minor tweaks for improving the animation. */
    public static boolean qsbAnimationMinorFixes() {
        return sFeatureFlags.qsbAnimationMinorFixes();
    }

    public static final String FLAG_REDUCE_WORKSPACE_BLUR_USAGE = "com.android.launcher3.reduce_workspace_blur_usage";
    /** Disables the full workspace blur and zoom effects behind surfaces like the \ */
    public static boolean reduceWorkspaceBlurUsage() {
        return sFeatureFlags.reduceWorkspaceBlurUsage();
    }

    public static final String FLAG_RESTORE_ARCHIVED_APP_ICONS_FROM_DB = "com.android.launcher3.restore_archived_app_icons_from_db";
    /** Restores pre-archived icons from db when available, mimicing promise icons */
    public static boolean restoreArchivedAppIconsFromDb() {
        return sFeatureFlags.restoreArchivedAppIconsFromDb();
    }

    public static final String FLAG_SHOW_CREATE_WIDGET_BTN_IN_PICKER = "com.android.launcher3.show_create_widget_btn_in_picker";
    /** Shows create widget button in widget picker */
    public static boolean showCreateWidgetBtnInPicker() {
        return sFeatureFlags.showCreateWidgetBtnInPicker();
    }

    public static final String FLAG_SHOW_FILES_ON_HOME_SCREEN = "com.android.launcher3.show_files_on_home_screen";
    /** Enables file and folder items on the home screen */
    public static boolean showFilesOnHomeScreen() {
        return sFeatureFlags.showFilesOnHomeScreen();
    }

    public static final String FLAG_SIMPLIFIED_LAUNCHER_MODEL_BINDING = "com.android.launcher3.simplified_launcher_model_binding";
    /** Simplified approach to binding launcher model asynchronously */
    public static boolean simplifiedLauncherModelBinding() {
        return sFeatureFlags.simplifiedLauncherModelBinding();
    }

    public static final String FLAG_TASKBAR_QUIET_MODE_CHANGE_SUPPORT = "com.android.launcher3.taskbar_quiet_mode_change_support";
    /** Support changing quiet mode for user profiles in taskbar. */
    public static boolean taskbarQuietModeChangeSupport() {
        return sFeatureFlags.taskbarQuietModeChangeSupport();
    }

    public static final String FLAG_TOOLTIP_EDU_COMBINATOR = "com.android.launcher3.tooltip_edu_combinator";
    /** Separate logic of education tooltip combination from presentation */
    public static boolean tooltipEduCombinator() {
        return sFeatureFlags.tooltipEduCombinator();
    }

    public static final String FLAG_TRANSLATE_IMESWITCHER_3BUTTONS_WITH_BUBBLE = "com.android.launcher3.translate_imeswitcher_3buttons_with_bubble";
    /** Translate the IME Switcher when 3-buttons Navigation with Bubble Icon */
    public static boolean translateImeswitcher3ButtonsWithBubble() {
        return sFeatureFlags.translateImeswitcher3ButtonsWithBubble();
    }

    public static final String FLAG_UPDATE_RECENTS_WM_WWM_CONFIGURATION = "com.android.launcher3.update_recents_wm_wwm_configuration";
    /** Bugfix for missing configurations in RWM */
    public static boolean updateRecentsWmWwmConfiguration() {
        return sFeatureFlags.updateRecentsWmWwmConfiguration();
    }

    public static final String FLAG_WIDGET_RETURN_ANIMATION_MINOR_FIXES = "com.android.launcher3.widget_return_animation_minor_fixes";
    /** Fixed return animation for launcher widgets. Did some minor tweaks for improving the animation. */
    public static boolean widgetReturnAnimationMinorFixes() {
        return sFeatureFlags.widgetReturnAnimationMinorFixes();
    }

}
