/* Generated by generate_flags.py - Do not edit directly */
package com.sandboxr.launcher.config

import com.android.launcher3.Flags as AospFlags

/**
 * Sandboxr-namespaced feature flag registry.
 */
object Flags {
    const val FLAG_ALL_APPS_SURFACE: String = AospFlags.FLAG_ALL_APPS_SURFACE
    @JvmStatic
    fun allAppsSurface(): Boolean = AospFlags.allAppsSurface()

    const val FLAG_APP_LAUNCH_BLUR: String = AospFlags.FLAG_APP_LAUNCH_BLUR
    @JvmStatic
    fun appLaunchBlur(): Boolean = AospFlags.appLaunchBlur()

    const val FLAG_AVOID_DISPLAY_CUTOUT_BUBBLE_BAR: String = AospFlags.FLAG_AVOID_DISPLAY_CUTOUT_BUBBLE_BAR
    @JvmStatic
    fun avoidDisplayCutoutBubbleBar(): Boolean = AospFlags.avoidDisplayCutoutBubbleBar()

    const val FLAG_BIND_MODEL_USING_REPOSITORY: String = AospFlags.FLAG_BIND_MODEL_USING_REPOSITORY
    @JvmStatic
    fun bindModelUsingRepository(): Boolean = AospFlags.bindModelUsingRepository()

    const val FLAG_BLUR_ON_MORE_SURFACES: String = AospFlags.FLAG_BLUR_ON_MORE_SURFACES
    @JvmStatic
    fun blurOnMoreSurfaces(): Boolean = AospFlags.blurOnMoreSurfaces()

    const val FLAG_BLURRED_HOME_ANIMATION: String = AospFlags.FLAG_BLURRED_HOME_ANIMATION
    @JvmStatic
    fun blurredHomeAnimation(): Boolean = AospFlags.blurredHomeAnimation()

    const val FLAG_CENTER_SPRING_LOADED_STATE_VERTICALLY: String = AospFlags.FLAG_CENTER_SPRING_LOADED_STATE_VERTICALLY
    @JvmStatic
    fun centerSpringLoadedStateVertically(): Boolean = AospFlags.centerSpringLoadedStateVertically()

    const val FLAG_CONDO_PLANNER: String = AospFlags.FLAG_CONDO_PLANNER
    @JvmStatic
    fun condoPlanner(): Boolean = AospFlags.condoPlanner()

    const val FLAG_DISABLE_APP_AUTOMATION_BLUR: String = AospFlags.FLAG_DISABLE_APP_AUTOMATION_BLUR
    @JvmStatic
    fun disableAppAutomationBlur(): Boolean = AospFlags.disableAppAutomationBlur()

    const val FLAG_DOUBLE_TAP_TO_SLEEP: String = AospFlags.FLAG_DOUBLE_TAP_TO_SLEEP
    @JvmStatic
    fun doubleTapToSleep(): Boolean = AospFlags.doubleTapToSleep()

    const val FLAG_ENABLE_ALL_APPS_BUTTON_IN_HOTSEAT: String = AospFlags.FLAG_ENABLE_ALL_APPS_BUTTON_IN_HOTSEAT
    @JvmStatic
    fun enableAllAppsButtonInHotseat(): Boolean = AospFlags.enableAllAppsButtonInHotseat()

    const val FLAG_ENABLE_ALL_APPS_EDU_FOR_OVERSWIPE: String = AospFlags.FLAG_ENABLE_ALL_APPS_EDU_FOR_OVERSWIPE
    @JvmStatic
    fun enableAllAppsEduForOverswipe(): Boolean = AospFlags.enableAllAppsEduForOverswipe()

    const val FLAG_ENABLE_ALT_TAB_KQS_FLATENNING: String = AospFlags.FLAG_ENABLE_ALT_TAB_KQS_FLATENNING
    @JvmStatic
    fun enableAltTabKqsFlatenning(): Boolean = AospFlags.enableAltTabKqsFlatenning()

    const val FLAG_ENABLE_APP_AUTOMATION_INDICATOR: String = AospFlags.FLAG_ENABLE_APP_AUTOMATION_INDICATOR
    @JvmStatic
    fun enableAppAutomationIndicator(): Boolean = AospFlags.enableAppAutomationIndicator()

    const val FLAG_ENABLE_APP_LOCK_SHORTCUT: String = AospFlags.FLAG_ENABLE_APP_LOCK_SHORTCUT
    @JvmStatic
    fun enableAppLockShortcut(): Boolean = AospFlags.enableAppLockShortcut()

    const val FLAG_ENABLE_COLLAPSE_SYSUI_PANELS_ON_TASKBAR_CLICK: String = AospFlags.FLAG_ENABLE_COLLAPSE_SYSUI_PANELS_ON_TASKBAR_CLICK
    @JvmStatic
    fun enableCollapseSysuiPanelsOnTaskbarClick(): Boolean = AospFlags.enableCollapseSysuiPanelsOnTaskbarClick()

    const val FLAG_ENABLE_COMPOSE_FOR_OPTIONS_POPUP_MENU_DIALOG: String = AospFlags.FLAG_ENABLE_COMPOSE_FOR_OPTIONS_POPUP_MENU_DIALOG
    @JvmStatic
    fun enableComposeForOptionsPopupMenuDialog(): Boolean = AospFlags.enableComposeForOptionsPopupMenuDialog()

    const val FLAG_ENABLE_CONTRAST_TILES: String = AospFlags.FLAG_ENABLE_CONTRAST_TILES
    @JvmStatic
    fun enableContrastTiles(): Boolean = AospFlags.enableContrastTiles()

    const val FLAG_ENABLE_CUE_BAR_DESKTOP_FORM_FACTOR: String = AospFlags.FLAG_ENABLE_CUE_BAR_DESKTOP_FORM_FACTOR
    @JvmStatic
    fun enableCueBarDesktopFormFactor(): Boolean = AospFlags.enableCueBarDesktopFormFactor()

    const val FLAG_ENABLE_CURSOR_DRIVEN_WORKFLOWS: String = AospFlags.FLAG_ENABLE_CURSOR_DRIVEN_WORKFLOWS
    @JvmStatic
    fun enableCursorDrivenWorkflows(): Boolean = AospFlags.enableCursorDrivenWorkflows()

    const val FLAG_ENABLE_CUSTOM_HEIGHT_FOR_ALL_APPS_ON_CD: String = AospFlags.FLAG_ENABLE_CUSTOM_HEIGHT_FOR_ALL_APPS_ON_CD
    @JvmStatic
    fun enableCustomHeightForAllAppsOnCd(): Boolean = AospFlags.enableCustomHeightForAllAppsOnCd()

    const val FLAG_ENABLE_DRAG_START_END_MULTI_DISPATCH: String = AospFlags.FLAG_ENABLE_DRAG_START_END_MULTI_DISPATCH
    @JvmStatic
    fun enableDragStartEndMultiDispatch(): Boolean = AospFlags.enableDragStartEndMultiDispatch()

    const val FLAG_ENABLE_EXPANDING_PAUSE_WORK_BUTTON: String = AospFlags.FLAG_ENABLE_EXPANDING_PAUSE_WORK_BUTTON
    @JvmStatic
    fun enableExpandingPauseWorkButton(): Boolean = AospFlags.enableExpandingPauseWorkButton()

    const val FLAG_ENABLE_EXPRESSIVE_FOLDER_EXPANSION: String = AospFlags.FLAG_ENABLE_EXPRESSIVE_FOLDER_EXPANSION
    @JvmStatic
    fun enableExpressiveFolderExpansion(): Boolean = AospFlags.enableExpressiveFolderExpansion()

    const val FLAG_ENABLE_FALLBACK_OVERVIEW_IN_WINDOW: String = AospFlags.FLAG_ENABLE_FALLBACK_OVERVIEW_IN_WINDOW
    @JvmStatic
    fun enableFallbackOverviewInWindow(): Boolean = AospFlags.enableFallbackOverviewInWindow()

    const val FLAG_ENABLE_FILE_SYSTEM_FOLDERS_AS_DROP_TARGETS: String = AospFlags.FLAG_ENABLE_FILE_SYSTEM_FOLDERS_AS_DROP_TARGETS
    @JvmStatic
    fun enableFileSystemFoldersAsDropTargets(): Boolean = AospFlags.enableFileSystemFoldersAsDropTargets()

    const val FLAG_ENABLE_FIXED_QSB_AT_BOTTOM: String = AospFlags.FLAG_ENABLE_FIXED_QSB_AT_BOTTOM
    @JvmStatic
    fun enableFixedQsbAtBottom(): Boolean = AospFlags.enableFixedQsbAtBottom()

    const val FLAG_ENABLE_FOCUS_OUTLINE: String = AospFlags.FLAG_ENABLE_FOCUS_OUTLINE
    @JvmStatic
    fun enableFocusOutline(): Boolean = AospFlags.enableFocusOutline()

    const val FLAG_ENABLE_FOLDER_REFACTOR: String = AospFlags.FLAG_ENABLE_FOLDER_REFACTOR
    @JvmStatic
    fun enableFolderRefactor(): Boolean = AospFlags.enableFolderRefactor()

    const val FLAG_ENABLE_GROWTH_NUDGE: String = AospFlags.FLAG_ENABLE_GROWTH_NUDGE
    @JvmStatic
    fun enableGrowthNudge(): Boolean = AospFlags.enableGrowthNudge()

    const val FLAG_ENABLE_HOME_SCREEN_FILES_COPY_PASTE: String = AospFlags.FLAG_ENABLE_HOME_SCREEN_FILES_COPY_PASTE
    @JvmStatic
    fun enableHomeScreenFilesCopyPaste(): Boolean = AospFlags.enableHomeScreenFilesCopyPaste()

    const val FLAG_ENABLE_HOME_SCREEN_FILES_RENAMING: String = AospFlags.FLAG_ENABLE_HOME_SCREEN_FILES_RENAMING
    @JvmStatic
    fun enableHomeScreenFilesRenaming(): Boolean = AospFlags.enableHomeScreenFilesRenaming()

    const val FLAG_ENABLE_HOME_SCREEN_FILES_TRASHING: String = AospFlags.FLAG_ENABLE_HOME_SCREEN_FILES_TRASHING
    @JvmStatic
    fun enableHomeScreenFilesTrashing(): Boolean = AospFlags.enableHomeScreenFilesTrashing()

    const val FLAG_ENABLE_KQS_FORCE_TAKE_RUNNING_TASK_THUMBNAIL: String = AospFlags.FLAG_ENABLE_KQS_FORCE_TAKE_RUNNING_TASK_THUMBNAIL
    @JvmStatic
    fun enableKqsForceTakeRunningTaskThumbnail(): Boolean = AospFlags.enableKqsForceTakeRunningTaskThumbnail()

    const val FLAG_ENABLE_LATER_IS_LOCKED_CHECK: String = AospFlags.FLAG_ENABLE_LATER_IS_LOCKED_CHECK
    @JvmStatic
    fun enableLaterIsLockedCheck(): Boolean = AospFlags.enableLaterIsLockedCheck()

    const val FLAG_ENABLE_LAUNCHER_ICON_SHAPES: String = AospFlags.FLAG_ENABLE_LAUNCHER_ICON_SHAPES
    @JvmStatic
    fun enableLauncherIconShapes(): Boolean = AospFlags.enableLauncherIconShapes()

    const val FLAG_ENABLE_LAUNCHER_OVERVIEW_IN_WINDOW: String = AospFlags.FLAG_ENABLE_LAUNCHER_OVERVIEW_IN_WINDOW
    @JvmStatic
    fun enableLauncherOverviewInWindow(): Boolean = AospFlags.enableLauncherOverviewInWindow()

    const val FLAG_ENABLE_LOW_RES_THUMBNAIL_PRELOADING: String = AospFlags.FLAG_ENABLE_LOW_RES_THUMBNAIL_PRELOADING
    @JvmStatic
    fun enableLowResThumbnailPreloading(): Boolean = AospFlags.enableLowResThumbnailPreloading()

    const val FLAG_ENABLE_MOUSE_INTERACTION_CHANGES: String = AospFlags.FLAG_ENABLE_MOUSE_INTERACTION_CHANGES
    @JvmStatic
    fun enableMouseInteractionChanges(): Boolean = AospFlags.enableMouseInteractionChanges()

    const val FLAG_ENABLE_MULTI_INSTANCE_MENU_TASKBAR: String = AospFlags.FLAG_ENABLE_MULTI_INSTANCE_MENU_TASKBAR
    @JvmStatic
    fun enableMultiInstanceMenuTaskbar(): Boolean = AospFlags.enableMultiInstanceMenuTaskbar()

    const val FLAG_ENABLE_NARROW_GRID_RESTORE: String = AospFlags.FLAG_ENABLE_NARROW_GRID_RESTORE
    @JvmStatic
    fun enableNarrowGridRestore(): Boolean = AospFlags.enableNarrowGridRestore()

    const val FLAG_ENABLE_NEW_TOUCHPAD_GESTURES: String = AospFlags.FLAG_ENABLE_NEW_TOUCHPAD_GESTURES
    @JvmStatic
    fun enableNewTouchpadGestures(): Boolean = AospFlags.enableNewTouchpadGestures()

    const val FLAG_ENABLE_OVERVIEW_DESKTOP_TILE_WALLPAPER_BACKGROUND: String = AospFlags.FLAG_ENABLE_OVERVIEW_DESKTOP_TILE_WALLPAPER_BACKGROUND
    @JvmStatic
    fun enableOverviewDesktopTileWallpaperBackground(): Boolean = AospFlags.enableOverviewDesktopTileWallpaperBackground()

    const val FLAG_ENABLE_OVERVIEW_PAGINATION: String = AospFlags.FLAG_ENABLE_OVERVIEW_PAGINATION
    @JvmStatic
    fun enableOverviewPagination(): Boolean = AospFlags.enableOverviewPagination()

    const val FLAG_ENABLE_OVERVIEW_SELECT_TEXT_VIEW: String = AospFlags.FLAG_ENABLE_OVERVIEW_SELECT_TEXT_VIEW
    @JvmStatic
    fun enableOverviewSelectTextView(): Boolean = AospFlags.enableOverviewSelectTextView()

    const val FLAG_ENABLE_PREDICTIVE_BACK_IN_OVERVIEW: String = AospFlags.FLAG_ENABLE_PREDICTIVE_BACK_IN_OVERVIEW
    @JvmStatic
    fun enablePredictiveBackInOverview(): Boolean = AospFlags.enablePredictiveBackInOverview()

    const val FLAG_ENABLE_PRIVATE_SPACE: String = AospFlags.FLAG_ENABLE_PRIVATE_SPACE
    @JvmStatic
    fun enablePrivateSpace(): Boolean = AospFlags.enablePrivateSpace()

    const val FLAG_ENABLE_QSB_ON_HOTSEAT: String = AospFlags.FLAG_ENABLE_QSB_ON_HOTSEAT
    @JvmStatic
    fun enableQsbOnHotseat(): Boolean = AospFlags.enableQsbOnHotseat()

    const val FLAG_ENABLE_REBOOT_UNLOCK_ANIMATION: String = AospFlags.FLAG_ENABLE_REBOOT_UNLOCK_ANIMATION
    @JvmStatic
    fun enableRebootUnlockAnimation(): Boolean = AospFlags.enableRebootUnlockAnimation()

    const val FLAG_ENABLE_RECENTS_WINDOW_BLUR: String = AospFlags.FLAG_ENABLE_RECENTS_WINDOW_BLUR
    @JvmStatic
    fun enableRecentsWindowBlur(): Boolean = AospFlags.enableRecentsWindowBlur()

    const val FLAG_ENABLE_RECENTS_WINDOW_PROTO_LOG: String = AospFlags.FLAG_ENABLE_RECENTS_WINDOW_PROTO_LOG
    @JvmStatic
    fun enableRecentsWindowProtoLog(): Boolean = AospFlags.enableRecentsWindowProtoLog()

    const val FLAG_ENABLE_REFACTOR_DIGITAL_WELLBEING_TOAST: String = AospFlags.FLAG_ENABLE_REFACTOR_DIGITAL_WELLBEING_TOAST
    @JvmStatic
    fun enableRefactorDigitalWellbeingToast(): Boolean = AospFlags.enableRefactorDigitalWellbeingToast()

    const val FLAG_ENABLE_RESPONSIVE_WORKSPACE: String = AospFlags.FLAG_ENABLE_RESPONSIVE_WORKSPACE
    @JvmStatic
    fun enableResponsiveWorkspace(): Boolean = AospFlags.enableResponsiveWorkspace()

    const val FLAG_ENABLE_RESTOREDBTASK_MODELWRITER_REFACTOR: String = AospFlags.FLAG_ENABLE_RESTOREDBTASK_MODELWRITER_REFACTOR
    @JvmStatic
    fun enableRestoredbtaskModelwriterRefactor(): Boolean = AospFlags.enableRestoredbtaskModelwriterRefactor()

    const val FLAG_ENABLE_REVERSIBLE_HOME_ACTION_CORNER: String = AospFlags.FLAG_ENABLE_REVERSIBLE_HOME_ACTION_CORNER
    @JvmStatic
    fun enableReversibleHomeActionCorner(): Boolean = AospFlags.enableReversibleHomeActionCorner()

    const val FLAG_ENABLE_SAVE_ACTION_IN_OVERVIEW_SHARE: String = AospFlags.FLAG_ENABLE_SAVE_ACTION_IN_OVERVIEW_SHARE
    @JvmStatic
    fun enableSaveActionInOverviewShare(): Boolean = AospFlags.enableSaveActionInOverviewShare()

    const val FLAG_ENABLE_SCALABILITY_FOR_DESKTOP_EXPERIENCE: String = AospFlags.FLAG_ENABLE_SCALABILITY_FOR_DESKTOP_EXPERIENCE
    @JvmStatic
    fun enableScalabilityForDesktopExperience(): Boolean = AospFlags.enableScalabilityForDesktopExperience()

    const val FLAG_ENABLE_SIMULTANEOUS_OVERVIEW_TRIGGER_ON_EXTENDED_DESKTOP: String = AospFlags.FLAG_ENABLE_SIMULTANEOUS_OVERVIEW_TRIGGER_ON_EXTENDED_DESKTOP
    @JvmStatic
    fun enableSimultaneousOverviewTriggerOnExtendedDesktop(): Boolean = AospFlags.enableSimultaneousOverviewTriggerOnExtendedDesktop()

    const val FLAG_ENABLE_STATE_MANAGER_PROTO_LOG: String = AospFlags.FLAG_ENABLE_STATE_MANAGER_PROTO_LOG
    @JvmStatic
    fun enableStateManagerProtoLog(): Boolean = AospFlags.enableStateManagerProtoLog()

    const val FLAG_ENABLE_STRICT_MODE: String = AospFlags.FLAG_ENABLE_STRICT_MODE
    @JvmStatic
    fun enableStrictMode(): Boolean = AospFlags.enableStrictMode()

    const val FLAG_ENABLE_SUPPORT_FOR_ARCHIVING: String = AospFlags.FLAG_ENABLE_SUPPORT_FOR_ARCHIVING
    @JvmStatic
    fun enableSupportForArchiving(): Boolean = AospFlags.enableSupportForArchiving()

    const val FLAG_ENABLE_SWIPE_UP_MAGNETIC_DETACH: String = AospFlags.FLAG_ENABLE_SWIPE_UP_MAGNETIC_DETACH
    @JvmStatic
    fun enableSwipeUpMagneticDetach(): Boolean = AospFlags.enableSwipeUpMagneticDetach()

    const val FLAG_ENABLE_SYSTEM_DRAG: String = AospFlags.FLAG_ENABLE_SYSTEM_DRAG
    @JvmStatic
    fun enableSystemDrag(): Boolean = AospFlags.enableSystemDrag()

    const val FLAG_ENABLE_SYSTEM_DRAG_TO_OTHER_APPS: String = AospFlags.FLAG_ENABLE_SYSTEM_DRAG_TO_OTHER_APPS
    @JvmStatic
    fun enableSystemDragToOtherApps(): Boolean = AospFlags.enableSystemDragToOtherApps()

    const val FLAG_ENABLE_TASKBAR_A11Y_MORE_OPTIONS_BUTTON: String = AospFlags.FLAG_ENABLE_TASKBAR_A11Y_MORE_OPTIONS_BUTTON
    @JvmStatic
    fun enableTaskbarA11YMoreOptionsButton(): Boolean = AospFlags.enableTaskbarA11YMoreOptionsButton()

    const val FLAG_ENABLE_TASKBAR_BEHIND_SHADE: String = AospFlags.FLAG_ENABLE_TASKBAR_BEHIND_SHADE
    @JvmStatic
    fun enableTaskbarBehindShade(): Boolean = AospFlags.enableTaskbarBehindShade()

    const val FLAG_ENABLE_TASKBAR_CUSTOMIZATION: String = AospFlags.FLAG_ENABLE_TASKBAR_CUSTOMIZATION
    @JvmStatic
    fun enableTaskbarCustomization(): Boolean = AospFlags.enableTaskbarCustomization()

    const val FLAG_ENABLE_TASKBAR_DRAG_AND_DROP: String = AospFlags.FLAG_ENABLE_TASKBAR_DRAG_AND_DROP
    @JvmStatic
    fun enableTaskbarDragAndDrop(): Boolean = AospFlags.enableTaskbarDragAndDrop()

    const val FLAG_ENABLE_TASKBAR_DRAG_TO_REMOVE: String = AospFlags.FLAG_ENABLE_TASKBAR_DRAG_TO_REMOVE
    @JvmStatic
    fun enableTaskbarDragToRemove(): Boolean = AospFlags.enableTaskbarDragToRemove()

    const val FLAG_ENABLE_TASKBAR_ICON_CONTAINER: String = AospFlags.FLAG_ENABLE_TASKBAR_ICON_CONTAINER
    @JvmStatic
    fun enableTaskbarIconContainer(): Boolean = AospFlags.enableTaskbarIconContainer()

    const val FLAG_ENABLE_TASKBAR_ICON_DESKTOP_CLICKS: String = AospFlags.FLAG_ENABLE_TASKBAR_ICON_DESKTOP_CLICKS
    @JvmStatic
    fun enableTaskbarIconDesktopClicks(): Boolean = AospFlags.enableTaskbarIconDesktopClicks()

    const val FLAG_ENABLE_TASKBAR_NO_RECREATE: String = AospFlags.FLAG_ENABLE_TASKBAR_NO_RECREATE
    @JvmStatic
    fun enableTaskbarNoRecreate(): Boolean = AospFlags.enableTaskbarNoRecreate()

    const val FLAG_ENABLE_TASKBAR_PINNING: String = AospFlags.FLAG_ENABLE_TASKBAR_PINNING
    @JvmStatic
    fun enableTaskbarPinning(): Boolean = AospFlags.enableTaskbarPinning()

    const val FLAG_ENABLE_TASKBAR_UI_THREAD: String = AospFlags.FLAG_ENABLE_TASKBAR_UI_THREAD
    @JvmStatic
    fun enableTaskbarUiThread(): Boolean = AospFlags.enableTaskbarUiThread()

    const val FLAG_ENABLE_TASKS_DRAG_AND_DROP_IN_OVERVIEW: String = AospFlags.FLAG_ENABLE_TASKS_DRAG_AND_DROP_IN_OVERVIEW
    @JvmStatic
    fun enableTasksDragAndDropInOverview(): Boolean = AospFlags.enableTasksDragAndDropInOverview()

    const val FLAG_ENABLE_TRANSACTIONAL_MODEL_WRITER: String = AospFlags.FLAG_ENABLE_TRANSACTIONAL_MODEL_WRITER
    @JvmStatic
    fun enableTransactionalModelWriter(): Boolean = AospFlags.enableTransactionalModelWriter()

    const val FLAG_ENABLE_TWO_PANE_LAUNCHER_SETTINGS: String = AospFlags.FLAG_ENABLE_TWO_PANE_LAUNCHER_SETTINGS
    @JvmStatic
    fun enableTwoPaneLauncherSettings(): Boolean = AospFlags.enableTwoPaneLauncherSettings()

    const val FLAG_ENABLE_TWOLINE_ALLAPPS: String = AospFlags.FLAG_ENABLE_TWOLINE_ALLAPPS
    @JvmStatic
    fun enableTwolineAllapps(): Boolean = AospFlags.enableTwolineAllapps()

    const val FLAG_ENABLE_TWOLINE_TOGGLE: String = AospFlags.FLAG_ENABLE_TWOLINE_TOGGLE
    @JvmStatic
    fun enableTwolineToggle(): Boolean = AospFlags.enableTwolineToggle()

    const val FLAG_ENABLE_UNFOLD_STATE_ANIMATION: String = AospFlags.FLAG_ENABLE_UNFOLD_STATE_ANIMATION
    @JvmStatic
    fun enableUnfoldStateAnimation(): Boolean = AospFlags.enableUnfoldStateAnimation()

    const val FLAG_ENABLE_WIDGET_PICKER_BLUR: String = AospFlags.FLAG_ENABLE_WIDGET_PICKER_BLUR
    @JvmStatic
    fun enableWidgetPickerBlur(): Boolean = AospFlags.enableWidgetPickerBlur()

    const val FLAG_ENABLE_WIDGETS_SECTION_IN_OPTIONS_MENU: String = AospFlags.FLAG_ENABLE_WIDGETS_SECTION_IN_OPTIONS_MENU
    @JvmStatic
    fun enableWidgetsSectionInOptionsMenu(): Boolean = AospFlags.enableWidgetsSectionInOptionsMenu()

    const val FLAG_ENABLE_WORKSPACE_PAGE_ANIMATION: String = AospFlags.FLAG_ENABLE_WORKSPACE_PAGE_ANIMATION
    @JvmStatic
    fun enableWorkspacePageAnimation(): Boolean = AospFlags.enableWorkspacePageAnimation()

    const val FLAG_ENABLE_WORKSPACE_SELECTION: String = AospFlags.FLAG_ENABLE_WORKSPACE_SELECTION
    @JvmStatic
    fun enableWorkspaceSelection(): Boolean = AospFlags.enableWorkspaceSelection()

    const val FLAG_ENABLED_FOLDERS_IN_ALL_APPS: String = AospFlags.FLAG_ENABLED_FOLDERS_IN_ALL_APPS
    @JvmStatic
    fun enabledFoldersInAllApps(): Boolean = AospFlags.enabledFoldersInAllApps()

    const val FLAG_EXPANDABLE_LONG_PRESS_MENU: String = AospFlags.FLAG_EXPANDABLE_LONG_PRESS_MENU
    @JvmStatic
    fun expandableLongPressMenu(): Boolean = AospFlags.expandableLongPressMenu()

    const val FLAG_FALLBACK_REVEAL_ANIMATION: String = AospFlags.FLAG_FALLBACK_REVEAL_ANIMATION
    @JvmStatic
    fun fallbackRevealAnimation(): Boolean = AospFlags.fallbackRevealAnimation()

    const val FLAG_FIX_WIDGET_SINGLE_PTR_RESIZE: String = AospFlags.FLAG_FIX_WIDGET_SINGLE_PTR_RESIZE
    @JvmStatic
    fun fixWidgetSinglePtrResize(): Boolean = AospFlags.fixWidgetSinglePtrResize()

    const val FLAG_FLOATING_SEARCH_BAR: String = AospFlags.FLAG_FLOATING_SEARCH_BAR
    @JvmStatic
    fun floatingSearchBar(): Boolean = AospFlags.floatingSearchBar()

    const val FLAG_FORCE_MONOCHROME_APP_ICONS: String = AospFlags.FLAG_FORCE_MONOCHROME_APP_ICONS
    @JvmStatic
    fun forceMonochromeAppIcons(): Boolean = AospFlags.forceMonochromeAppIcons()

    const val FLAG_FORCE_MONOCHROME_APP_ICONS_ADAPT_COLORS: String = AospFlags.FLAG_FORCE_MONOCHROME_APP_ICONS_ADAPT_COLORS
    @JvmStatic
    fun forceMonochromeAppIconsAdaptColors(): Boolean = AospFlags.forceMonochromeAppIconsAdaptColors()

    const val FLAG_GESTURE_NAV_TOUCH_INPUT_OPTIMIZATIONS: String = AospFlags.FLAG_GESTURE_NAV_TOUCH_INPUT_OPTIMIZATIONS
    @JvmStatic
    fun gestureNavTouchInputOptimizations(): Boolean = AospFlags.gestureNavTouchInputOptimizations()

    const val FLAG_HIDE_AUTOMATED_TASKS_IN_OVERVIEW: String = AospFlags.FLAG_HIDE_AUTOMATED_TASKS_IN_OVERVIEW
    @JvmStatic
    fun hideAutomatedTasksInOverview(): Boolean = AospFlags.hideAutomatedTasksInOverview()

    const val FLAG_HOME_SCREEN_EDIT_IMPROVEMENTS: String = AospFlags.FLAG_HOME_SCREEN_EDIT_IMPROVEMENTS
    @JvmStatic
    fun homeScreenEditImprovements(): Boolean = AospFlags.homeScreenEditImprovements()

    const val FLAG_IGNORE_THREE_FINGER_TRACKPAD_FOR_NAV_HANDLE_LONG_PRESS: String = AospFlags.FLAG_IGNORE_THREE_FINGER_TRACKPAD_FOR_NAV_HANDLE_LONG_PRESS
    @JvmStatic
    fun ignoreThreeFingerTrackpadForNavHandleLongPress(): Boolean = AospFlags.ignoreThreeFingerTrackpadForNavHandleLongPress()

    const val FLAG_LETTER_FAST_SCROLLER: String = AospFlags.FLAG_LETTER_FAST_SCROLLER
    @JvmStatic
    fun letterFastScroller(): Boolean = AospFlags.letterFastScroller()

    const val FLAG_MODEL_REPOSITORY: String = AospFlags.FLAG_MODEL_REPOSITORY
    @JvmStatic
    fun modelRepository(): Boolean = AospFlags.modelRepository()

    const val FLAG_MOVE_TO_REST_STATE_FOR_BACKGROUND_APP: String = AospFlags.FLAG_MOVE_TO_REST_STATE_FOR_BACKGROUND_APP
    @JvmStatic
    fun moveToRestStateForBackgroundApp(): Boolean = AospFlags.moveToRestStateForBackgroundApp()

    const val FLAG_MSDL_FEEDBACK: String = AospFlags.FLAG_MSDL_FEEDBACK
    @JvmStatic
    fun msdlFeedback(): Boolean = AospFlags.msdlFeedback()

    const val FLAG_NUDGE_PILL: String = AospFlags.FLAG_NUDGE_PILL
    @JvmStatic
    fun nudgePill(): Boolean = AospFlags.nudgePill()

    const val FLAG_ONE_GRID_ROTATION_HANDLING: String = AospFlags.FLAG_ONE_GRID_ROTATION_HANDLING
    @JvmStatic
    fun oneGridRotationHandling(): Boolean = AospFlags.oneGridRotationHandling()

    const val FLAG_ORIENTATION_FRIENDLY_DESKTOP_GRID_SPEC: String = AospFlags.FLAG_ORIENTATION_FRIENDLY_DESKTOP_GRID_SPEC
    @JvmStatic
    fun orientationFriendlyDesktopGridSpec(): Boolean = AospFlags.orientationFriendlyDesktopGridSpec()

    const val FLAG_PRIVATE_SPACE_ADD_FLOATING_MASK_VIEW: String = AospFlags.FLAG_PRIVATE_SPACE_ADD_FLOATING_MASK_VIEW
    @JvmStatic
    fun privateSpaceAddFloatingMaskView(): Boolean = AospFlags.privateSpaceAddFloatingMaskView()

    const val FLAG_PRIVATE_SPACE_ANIMATION: String = AospFlags.FLAG_PRIVATE_SPACE_ANIMATION
    @JvmStatic
    fun privateSpaceAnimation(): Boolean = AospFlags.privateSpaceAnimation()

    const val FLAG_QSB_ANIMATION_MINOR_FIXES: String = AospFlags.FLAG_QSB_ANIMATION_MINOR_FIXES
    @JvmStatic
    fun qsbAnimationMinorFixes(): Boolean = AospFlags.qsbAnimationMinorFixes()

    const val FLAG_REDUCE_WORKSPACE_BLUR_USAGE: String = AospFlags.FLAG_REDUCE_WORKSPACE_BLUR_USAGE
    @JvmStatic
    fun reduceWorkspaceBlurUsage(): Boolean = AospFlags.reduceWorkspaceBlurUsage()

    const val FLAG_RESTORE_ARCHIVED_APP_ICONS_FROM_DB: String = AospFlags.FLAG_RESTORE_ARCHIVED_APP_ICONS_FROM_DB
    @JvmStatic
    fun restoreArchivedAppIconsFromDb(): Boolean = AospFlags.restoreArchivedAppIconsFromDb()

    const val FLAG_SHOW_CREATE_WIDGET_BTN_IN_PICKER: String = AospFlags.FLAG_SHOW_CREATE_WIDGET_BTN_IN_PICKER
    @JvmStatic
    fun showCreateWidgetBtnInPicker(): Boolean = AospFlags.showCreateWidgetBtnInPicker()

    const val FLAG_SHOW_FILES_ON_HOME_SCREEN: String = AospFlags.FLAG_SHOW_FILES_ON_HOME_SCREEN
    @JvmStatic
    fun showFilesOnHomeScreen(): Boolean = AospFlags.showFilesOnHomeScreen()

    const val FLAG_SIMPLIFIED_LAUNCHER_MODEL_BINDING: String = AospFlags.FLAG_SIMPLIFIED_LAUNCHER_MODEL_BINDING
    @JvmStatic
    fun simplifiedLauncherModelBinding(): Boolean = AospFlags.simplifiedLauncherModelBinding()

    const val FLAG_TASKBAR_QUIET_MODE_CHANGE_SUPPORT: String = AospFlags.FLAG_TASKBAR_QUIET_MODE_CHANGE_SUPPORT
    @JvmStatic
    fun taskbarQuietModeChangeSupport(): Boolean = AospFlags.taskbarQuietModeChangeSupport()

    const val FLAG_TOOLTIP_EDU_COMBINATOR: String = AospFlags.FLAG_TOOLTIP_EDU_COMBINATOR
    @JvmStatic
    fun tooltipEduCombinator(): Boolean = AospFlags.tooltipEduCombinator()

    const val FLAG_TRANSLATE_IMESWITCHER_3BUTTONS_WITH_BUBBLE: String = AospFlags.FLAG_TRANSLATE_IMESWITCHER_3BUTTONS_WITH_BUBBLE
    @JvmStatic
    fun translateImeswitcher3ButtonsWithBubble(): Boolean = AospFlags.translateImeswitcher3ButtonsWithBubble()

    const val FLAG_UPDATE_RECENTS_WM_WWM_CONFIGURATION: String = AospFlags.FLAG_UPDATE_RECENTS_WM_WWM_CONFIGURATION
    @JvmStatic
    fun updateRecentsWmWwmConfiguration(): Boolean = AospFlags.updateRecentsWmWwmConfiguration()

    const val FLAG_WIDGET_RETURN_ANIMATION_MINOR_FIXES: String = AospFlags.FLAG_WIDGET_RETURN_ANIMATION_MINOR_FIXES
    @JvmStatic
    fun widgetReturnAnimationMinorFixes(): Boolean = AospFlags.widgetReturnAnimationMinorFixes()

}
